Add option to remove uid from CSVLogger file path.
deepmind/acme pull request #115
Opened 2021-05-16 13:24 UTC by ethanluoyc

Fixes #59

2021-05-17 10:20 UTC, sinopalnikov requested changes
Looks good, thanks! Could you add a simple unit test covering this change?

2021-05-17 10:23 UTC, ethanluoyc commented
> Looks good, thanks! Could you add a simple unit test covering this change?

I wanted to do that with absl parameterized tests. Is it ok if I change the base test case to inherit from that?

2021-05-17 10:49 UTC, sinopalnikov commented
> > Looks good, thanks! Could you add a simple unit test covering this change?
> 
> I wanted to do that with absl parameterized tests. Is it ok if I change the base test case to inherit from that?

Yes, sure!

2021-05-17 12:55 UTC, ethanluoyc commented
@sinopalnikov Done.

An unrelated note. Is it possible for the maintainers to add a `.gitignore` file to the repo? I have to locally exclude the __pycache__ and package files for my local development and it would be useful if there is a project-wide .gitignore set up. Another thing that would be useful is to add a pylintrc that can be used so that external contributors can lint their PRs. I believe using the one found [here](https://google.github.io/styleguide/pyguide.html) with some tweaks would suffice.

2021-05-18 06:08 UTC, sinopalnikov requested changes
Could you simplify the parameterized annotation?

2021-05-18 06:08 UTC, sinopalnikov commented on acme/utils/loggers/csv_test.py
> +  )
```suggestion
  @parameterized.parameters(True, False)
```

2021-05-18 07:16 UTC, sinopalnikov commented
> An unrelated note. Is it possible for the maintainers to add a `.gitignore` file to the repo? I have to locally exclude the **pycache** and package files for my local development and it would be useful if there is a project-wide .gitignore set up. Another thing that would be useful is to add a pylintrc that can be used so that external contributors can lint their PRs. I believe using the one found [here](https://google.github.io/styleguide/pyguide.html) with some tweaks would suffice.

Yep, we'll look into adding them shortly.

2021-05-18 13:26 UTC, sinopalnikov commented
ftr `.gitignore` and `.pylintrc` are now added:
https://github.com/deepmind/acme/commit/a6b4162701542ed08b0b911ffac7c69fcb1bb3c7

2021-05-18 13:30 UTC, ethanluoyc commented
@sinopalnikov I have applied the review changes.

2021-05-18 14:22 UTC, sinopalnikov approved these changes
All good, thanks!

2021-05-24 16:02 UTC, merged