Update Reverb dataset
deepmind/acme pull request #193
Opened 2022-01-12 14:37 UTC by markub3327

Hello,

instead of hardcoding the num_parallel_calls is better to use AUTOTUNE for maximising performance based on machine CPUs. Applied the batching after the interleave rather than before it for maximising performance too. Interleave builds up internal prefetch buffers and doing prefetch more times goes to off policyness.

Based on: https://github.com/deepmind/reverb/issues/90

Thanks.
Have a nice day.

2022-01-13 22:58 UTC, markub3327 commented
@nikolamomchev

It's solution of:  #186

2022-02-18 11:34 UTC, nikolamomchev reviewed
@markub3327 thanks for the pull request.

Performance improvements in this file are very valuable, but I have some concerns that I'd like to have addressed before approving:
* Performance of this could vary depending on the exact setup of Reverb (e.g. size of the observations, layout, etc). I'm worried that a change like this could improve one use-case while degrading another. So, before approving I'd like to verify that the change is not introducing significant performance degradations for our internal use-cases.
* Your change is disabling the option to manually tune `prefetch_size` and `num_parallel_calls`. I'd rather keep this option (see comments in the files).


In general, you have two performance-related changes in here.
  1) Allowing `num_parallel_calls` to be set to `tf.data.AUTOTUNE`. This is can be achieved with a small non-invasive change which keeps the default behavior and alleviates the concerns above. I've actually compiled a small change that does this and I'll try to submit it soon.
  2) Moving the `batch` call to be performed after interleaving. This is one that requires a bit more extensive testing on our side. In order to know if it is worth for us to do this, it would help if you have some proof that it actually helps your use-case. Do you know if (and how much) this particular change affected your performance?

2022-02-18 17:49 UTC, nikolamomchev commented on acme/datasets/reverb.py
> +  dataset = dataset.batch(batch_size, drop_remainder=True)
We implemented a small benchmark for this method: https://github.com/deepmind/acme/blob/master/acme/datasets/reverb_benchmark.py

I ran few experiments and according to the benchmark moving the batching here results in a very significant performance degradation (it's nearly 4x slower). Based on this, I'd rather not move the batch call outside of `_make_dataset`. Let me know if you observe something different.

2022-02-18 18:03 UTC, nikolamomchev commented on acme/datasets/reverb.py
> +      cycle_length=tf.data.AUTOTUNE,
FTR, `num_parallel_calls=tf.data.AUTOTUNE` works a bit slower on my machine than `num_parallel_calls=12`. This suggests that the change is not a "win for all" type of improvement. My suggestion is to keep the default behavior in order to not affect existing clients. We can still make it possible for you to pass `num_parallel_calls=tf.data.AUTOTUNE`. This should allow you to use this method for your use-case, WDYT?

2022-02-20 06:45 UTC, markub3327 commented on acme/datasets/reverb.py
> -  if prefetch_size:
Interleave has its own internal prefetch and using .prefetch() is doubly applied prefetch on the dataset.

2022-02-20 06:46 UTC, markub3327 commented on acme/datasets/reverb.py
> +  dataset = dataset.batch(batch_size, drop_remainder=True)
Ok.

2022-02-20 06:52 UTC, markub3327 commented on acme/datasets/reverb.py
> +  dataset = dataset.batch(batch_size, drop_remainder=True)
I tested on my own environment and did not see any performance degradation. Sorry I have not tested it with [acme/datasets/reverb_benchmark.py](https://github.com/deepmind/acme/blob/master/acme/datasets/reverb_benchmark.py)...

You may have a true.  :)

2022-02-20 06:58 UTC, markub3327 commented on acme/datasets/reverb.py
> +      cycle_length=tf.data.AUTOTUNE,
Ok.

2022-02-20 07:01 UTC, markub3327 commented on acme/datasets/reverb.py
> +      cycle_length=tf.data.AUTOTUNE,
Users can be informed about `tf.data.AUTOTUNE` option in the documentation of Acme.

2022-02-21 18:14 UTC, nikolamomchev commented on acme/datasets/reverb.py
> +      cycle_length=tf.data.AUTOTUNE,
Thanks for the feedback. I've added a docstring to this method and mentioned the posibility to set `num_parallel_calls` to `AUTOTUNE` there.

2022-02-21 18:14 UTC, nikolamomchev commented on acme/datasets/reverb.py
> -  if prefetch_size:
I'm still a bit hesitant to remove the feature as it provides finer control over prefetching and some clients might find it useful.

2022-02-21 18:14 UTC, nikolamomchev commented on acme/datasets/reverb.py
> +  dataset = dataset.batch(batch_size, drop_remainder=True)
It's perfectly normal that you did not test with reverb_benchmark as it was only added 3 days ago to specifically test this change. :)

I understand that you didn't notice performance degradation from moving the batching outside, but did you notice any improvement from doing it when using your environment? Or would you be fine with keeping this inside `_make_dataset`?

2022-02-21 18:18 UTC, markub3327 commented on acme/datasets/reverb.py
> +      cycle_length=tf.data.AUTOTUNE,
Thanks. :)

2022-02-21 18:19 UTC, nikolamomchev reviewed
I've just submitted https://github.com/deepmind/acme/commit/cb4938f7e73692b1b2683304eeaf4933b16275fd which should allow you to call `make_reverb_dataset(..., num_parallel_calls=tf.data.AUTOTUNE, ...)`. If you don't specify `prefetch_size` explicitly, no extra prefetching will happen.

Do you mind checking if this performs well enough for you? According to our benchmark it should be more performant than what you propose in this change (at least on the machines I used to run the benchmark).

2022-02-21 18:20 UTC, markub3327 commented on acme/datasets/reverb.py
> -  if prefetch_size:
Ok.

2022-02-21 18:30 UTC, markub3327 commented
Now, I fix all.

2022-02-21 20:20 UTC, markub3327 commented
## AntBulletEnv-v0

After about 75 000 steps of training, the learner agents achieve the maximum score, which is a very good result.

![W B Chart 21  2  2022, 21_18_21](https://user-images.githubusercontent.com/74611856/155021349-88e6dbbb-bee7-4350-b9c9-5883b1badf9a.png)

2022-02-22 09:46 UTC, nikolamomchev requested changes
@markub3327 

I believe https://github.com/deepmind/acme/commit/cb4938f7e73692b1b2683304eeaf4933b16275fd may be enough for you to just start using this method. It allows you to call `make_reverb_dataset(..., num_parallel_calls=tf.data.AUTOTUNE, ...)`. You can disable the prefetching by just not specifying `prefetch_size` when calling the method.

Do you mind checking if this performs well enough for you? According to our benchmark it should be more performant than what you propose in this change (at least on the machines I used to run the benchmark).

2022-02-22 09:48 UTC, nikolamomchev commented
> ## AntBulletEnv-v0
> After about 75 000 steps of training, the learner agents achieve a high score, which is a very good result, with SPI = 32.
> 
> ![W B Chart 21  2  2022, 21_18_21](https://user-images.githubusercontent.com/74611856/155021349-88e6dbbb-bee7-4350-b9c9-5883b1badf9a.png)

That's good news, but I'm not sure how this relates to this change. I thought this only has impact on the runtime, not on how well algorithms train. Did I miss something?

2022-02-22 11:13 UTC, markub3327 commented
The score is improving faster and the time of training is shorter. I don't talk about how the score was achieved but don't negatively impact training time.

2022-02-22 11:35 UTC, nikolamomchev commented
> The score is improving faster and the time of training is shorter. I don't talk about what the score was achieved but it doesn't negatively impact training time.

Sorry, @markub3327 but I'm missing context here:
* What are you comparing? What's faster compared to what?
* Is this a reply to https://github.com/deepmind/acme/pull/193#pullrequestreview-889534294 or https://github.com/deepmind/acme/pull/193#issuecomment-1047611218?

FWIW, I'm mostly interested in getting an answer on https://github.com/deepmind/acme/pull/193#pullrequestreview-889534294 as the answer may imply that we can close this pull request and you can use what's already submitted.

2022-02-22 13:10 UTC, markub3327 commented
Sorry. Yes, it's very well for me.

2022-02-22 14:56 UTC, closed without merging

2022-02-22 15:13 UTC, markub3327 commented
@nikolamomchev 
And what about merging?